easyhower/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('welcome.urls', namespace='welcome')),
    path('user/', include('user.urls', namespace='user')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
]

tasks/urls.py
from django.urls import path

from tasks import views

app_name = 'tasks'

urlpatterns = [
    path('tasks/', views.TasksView.as_view(), name='tasks'),
    path('create-task/', views.CreateTask.as_view(), name='create_task'),
    path('read-task/<int:task_id>/', views.ReadTask.as_view(), name='read_task'),
    path('update-task/<int:task_id>/', views.UpdateTask.as_view(), name='update_task'),
    path('delete-task/<int:task_id>/', views.DeleteTask.as_view(), name='delete_task'),
    path('complate-task/<int:task_id>/', views.ComplateTask.as_view(), name='complate_task'),
]

user/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from user import views

app_name = 'user'

urlpatterns = [
    path('login/', views.UserLogin.as_view(), name='login'),
    path('registration/', views.UserRegistration.as_view(), name='registration'),
    path('profile/', views.UserProfile.as_view(), name='profile'),
    path('password-change/', views.UserPasswordChange.as_view(), name='password_change'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

welcome/urls.py
from django.urls import path

from welcome import views

app_name = 'welcome'

urlpatterns = [
    path('', views.WelcomeIndex.as_view(), name='index'),
]

tasks/models.py
from django.db import models

from user.models import User


class Task(models.Model):
    name = models.CharField(max_length=64, blank=False, null=False, verbose_name='Название задачи')
    description = models.TextField(max_length=256, blank=True, null=True, verbose_name='Описание задачи')
    urgency = models.BooleanField(default=True, verbose_name='Срочность задачи')
    importancy = models.BooleanField(default=True, verbose_name='Важность задачи')
    is_active = models.BooleanField(default=True, verbose_name='Активна ли задача')

    owner = models.ForeignKey(to=User, on_delete=models.CASCADE, verbose_name='Владелец задачи')

    class Meta:
        db_table = 'task'
        verbose_name = 'Задание'
        verbose_name_plural = 'Задания'
        ordering = ('id',)

    def __str__(self) -> str:
        return f"{self.name}"
    
    

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    complate_tasks_quantity = models.PositiveIntegerField(verbose_name='Количество выполненых задач', default=0)

    class Meta:
        db_table = 'user'
        verbose_name = 'Пользователя'
        verbose_name_plural = 'Пользователи'
        ordering = ('id',)

    def __str__(self) -> str:
        return f'{self.username}'

welcome/models.py
from django.db import models

# Create your models here.

tasks/forms.py
from django import forms

from tasks.models import Task


class CreateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'description', 'urgency', 'importancy']

    name = forms.CharField()
    description = forms.CharField()
    urgency = forms.ChoiceField(
        choices=[
            ("0", False),
            ("1", True)
        ]
    )
    importancy = forms.ChoiceField(
        choices=[
            ("0", False),
            ("1", True)
        ]
    )

class UpdateTaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['name', 'description', 'urgency', 'importancy']

    name = forms.CharField()
    description = forms.CharField()
    urgency = forms.ChoiceField(
        choices=[
            ("0", False),
            ("1", True)
        ]
    )
    importancy = forms.ChoiceField(
        choices=[
            ("0", False),
            ("1", True)
        ]
    )
    

user/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm

from user.models import User


class UserLoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = get_user_model()
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = (
            'username',
            'email',
            'password1',
            'password2',
            )
    
    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField()
    new_password1 = forms.CharField()
    new_password2 = forms.CharField()

tasks/views.py
from django.http import HttpResponseRedirect, JsonResponse
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from tasks.forms import CreateTaskForm, UpdateTaskForm
from tasks.models import Task


class TasksView(LoginRequiredMixin, ListView):
    template_name = "tasks/tasks.html"
    context_object_name = 'tasks'
    extra_context = {"title": "Easyhower - Задачи",}

    def get_queryset(self):
        return Task.objects.filter(owner=self.request.user, is_active=True)
        

class CreateTask(LoginRequiredMixin, CreateView):
    form_class = CreateTaskForm
    success_url = reverse_lazy("tasks:tasks")

    def form_valid(self, form):
        form.instance.owner = self.request.user

        return super().form_valid(form)


class ReadTask(LoginRequiredMixin, DetailView):
    pk_url_kwarg = 'task_id'
    template_name = 'tasks/includes/task_info.html'
    context_object_name = 'task'

    def get(self, request, task_id):
        task = self.get_object(task_id)
        task_info_html = render_to_string(
                self.template_name, 
                {self.context_object_name: task}, 
                request=request
            )

        response_data = {"html": task_info_html}

        return JsonResponse(response_data)
    
    def get_object(self, task_id, queryset=None):
        return Task.objects.get(id=task_id)
        

class UpdateTask(LoginRequiredMixin, UpdateView):
    model = Task
    form_class = UpdateTaskForm
    success_url = reverse_lazy('tasks:tasks')
    pk_url_kwarg = 'task_id'


class DeleteTask(LoginRequiredMixin, DeleteView):
    model = Task
    success_url = reverse_lazy('tasks:tasks')
    pk_url_kwarg = 'task_id'


class ComplateTask(LoginRequiredMixin, View):
    def get(self, request, task_id):
        task = self.get_object(task_id)
        task.is_active = False
        task.save()

        user = task.owner
        user.complate_tasks_quantity += 1
        user.save()

        return HttpResponseRedirect(reverse_lazy('tasks:tasks'))
    
    def get_object(self, task_id, queryset=None):
        return Task.objects.get(id=task_id)

user/views.py
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView
from django.views.generic import ListView
from django.contrib.auth.views import PasswordChangeView, LoginView
from django.contrib.auth.mixins import LoginRequiredMixin

from tasks.models import Task
from user.forms import UserLoginForm, UserPasswordChangeForm, UserRegistrationForm

# Create your views here.

class UserLogin(LoginView):
    template_name = 'user/login.html'
    form_class = UserLoginForm
    extra_context = {'title': 'Easyhower - Войти',}


class UserRegistration(CreateView):
    template_name = 'user/registration.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('user:profile')
    extra_context = {'title': 'Easyhower - Регистрация',}



class UserProfile(LoginRequiredMixin, ListView):
    template_name = 'user/profile.html'
    context_object_name = 'tasks'
    extra_context = {"title": "Easyhower - Профиль",}

    def get_queryset(self):
        return Task.objects.filter(owner=self.request.user, is_active=False)


class UserPasswordChange(PasswordChangeView):
    form_class = UserPasswordChangeForm
    success_url = reverse_lazy('user:profile')

welcome/views.py
from django.views.generic import TemplateView

# Create your views here.

class WelcomeIndex(TemplateView):
    template_name = 'welcome/index.html'
    extra_context = {'title': 'Easyhower - Главная'}

tasks/templates/tasks/includes/create_task.html
{% load static %}

<button class="btn btn_open-modal" data-target="add_task">
    <i class="fa fa-plus" aria-hidden="true"></i>
</button>

<article class="modal" id="add_task">
    <div class="modal__box">
        <hedaer class="modal__header">
            <h2 class="modal__h2">Добавить задачу</h2>
            <button class="btn btn_close-modal" data-target="add_task">
                <i class="fa fa-times" aria-hidden="true"></i></button>
        </hedaer>
        <div class="modal__body">
            <section class="tab active" id="add_task_form">
                <form action="{% url "tasks:create_task" %}" class="form" method="post">
                    {% csrf_token %}
                    <section class="form__item">
                        <label class="form__label" for="id_name">
                            <span class="form__text">Название задачи:</span>
                        </label>
                        <input type="text" name="name" class="form__input" id="id_name" required>
                    </section>

                    <section class="form__item">
                        <label class="form__label" for="id_description">
                            <span class="form__text">Описание задачи:</span>
                        </label>
                        <textarea class="form__input form__input_textarea" name="description"
                            id="id_description"></textarea>
                    </section>

                    <section class="form__item">
                        <span class="form__text">Срочность:</span>
                        <div class="form__wrapper">
                            <label class="form__label">
                                <input type="radio" name="urgency" value="1" class="form__radiobutton" id="id_urgency" required>
                                <span class="form__radiobutton-text">Срочно</span>
                            </label>
                            <label class="form__label">
                                <input type="radio" name="urgency" value="0" class="form__radiobutton" id="id_urgency">
                                <span class="form__radiobutton-text">Не срочно</span>
                            </label>
                        </div>
                    </section>

                    <section class="form__item">
                        <span class="form__text">Важность:</span>
                        <div class="form__wrapper">
                            <label class="form__label">
                                <input type="radio" name="importancy" value="1" class="form__radiobutton" id="id_importancy" required>
                                <span class="form__radiobutton-text">Важно</span>
                            </label>
                            <label class="form__label">
                                <input type="radio" name="importancy" value="0" class="form__radiobutton" id="id_importancy">
                                <span class="form__radiobutton-text">Не важно</span>
                            </label>
                        </div>
                    </section>

                    {% if form.errors %}
                    <section class="form__item form__item_errors">

                        {% for field, errors in form.errors.items %}
                            {% for error in errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        {% endfor %}
                    </section>
                        
                    {% endif %}

                    <button type="submit" class="btn form__submit">Добавить</button>
                </form>
            </section>

            <section class="tab" id="how-to-use">
                <h2 class="tab__h2">Что это?</h2>
                <div class="tab__text">
                    Матрица Эйзенхауэра представляет собой четыре квадранта, основанием которых служат две оси —
                    это ось важности (по вертикали) и ось срочности (по горизонтали). В итоге получается, что
                    каждый квадрант отличается своими качественными показателями. В каждый из квадрантов
                    записываются все задачи и дела, благодаря чему образуется предельно ясная и объективная
                    картина того, чем следует заняться в первую очередь, чем – во вторую, а чем вообще
                    заниматься не стоит.
                </div>
                <h2 class="tab__h2">Как пользоваться?</h2>
                <div class="tab__text">
                    Перед тем, как добавить новую задачу, задайте себе два вопроса: "Это срочно?" и "Это
                    важно?".
                    <br>
                    В категорию "Срочное и важное" следует добавить:
                    <ul class="tab__list">
                        <li>Горящие проекты,</li>
                        <li>проблемы со здоровьем,</li>
                        <li>экстренные ситуации.</li>
                    </ul>
                    В категорию "Не срочное и важное" следует добавить:
                    <ul class="tab__list">
                        <li>Основная деятельность в бизнесе или на работе,</li>
                        <li>повседневные дела, которые нельзя не делать.</li>
                    </ul>
                    В категорию "Срочное и не важное" следует добавить:
                    <ul class="tab__list">
                        <li>Рутинные дела</li>
                        <li>большинство звонков,</li>
                        <li>прочие отвлекающие факторы</li>
                    </ul>
                    В категорию "Не срочное и не важное" следует добавить:
                    <ul class="tab__list">
                        <li>Развлечения,</li>
                        <li>«пожиратели времени».</li>
                    </ul>
                </div>
            </section>
        </div>
        <footer class="modal__footer">
            <div class="tabs-switcher">
                <div class="tabs-switcher__item">
                    <button class="btn tabs-switcher__btn tabs-switcher__btn_open btn_how-to-use" data-next="tabs-switcher__btn_close" data-open="how-to-use"><i class="fa-solid fa-question tabs-switcher__icon"></i>Как пользоваться?</button>
                </div>
                <div class="tabs-switcher__item tabs-switcher__item_hidden">
                    <button class="btn tabs-switcher__btn tabs-switcher__btn_close" data-next="tabs-switcher__btn_open" data-open="add_task_form"><i class="fa-solid fa-arrow-left tabs-switcher__icon"></i>Назад</button>
                </div>
            </div>
        </footer>
    </div>
    <div class="modal__overlay"></div>
</article>

tasks/templates/tasks/includes/task_info.html
{% load static %}

<article class="modal" id="read_task">
    <div class="modal__box">
        <hedaer class="modal__header">
            <h2 class="modal__h2">Детали задачи</h2>
            <button class="btn btn_close-modal" data-target="read_task">
                <i class="fa fa-times" aria-hidden="true"></i>
            </button>
        </hedaer>
        <div class="modal__body">
            <section class="tab active" id="task_info">
                
                <div class="task-info">
                    <h2 class="task-info__h2">Название задачи</h2>
                    <p class="task-info__name">{{ task.name }}</p>
                    <h2 class="task-info__h2">Описание задачи</h2>
                    <p class="task-info__description">{{ task.description }}</p>
                    <h2 class="task-info__h2">Срочность задачи</h2>
                    <p class="task-info__urgency">{% if task.urgency %}Срочно{% else %}Не срочно{% endif %}</p>
                    <h2 class="task-info__h2">Важность задачи</h2>
                    <p class="task-info__importancy">{% if task.importancy %}Важно{% else %}Не важно{% endif %}</p>
                </div>
            </section>

            <section class="tab" id="update_task">
                <form action="{% url "tasks:update_task" task.id %}" class="form" method="post">
                    {% csrf_token %}
                    <section class="form__item">
                        <label class="form__label" for="id_name">
                            <span class="form__text">Название задачи:</span>
                        </label>
                        <input type="text" name="name" class="form__input" id="id_name" value="{{ task.name }}" required>
                    </section>

                    <section class="form__item">
                        <label class="form__label" for="id_description">
                            <span class="form__text">Описание задачи:</span>
                        </label>
                        <textarea class="form__input form__input_textarea" name="description" id="id_description">{{ task.description }}</textarea>
                    </section>

                    <section class="form__item">
                        <span class="form__text">Срочность:</span>
                        <div class="form__wrapper">
                            <label class="form__label">
                                <input type="radio" name="urgency" value="1" class="form__radiobutton" {% if task.urgency %}checked{% endif %} id="id_urgency" required>
                                <span class="form__radiobutton-text">Срочно</span>
                            </label>
                            <label class="form__label">
                                <input type="radio" name="urgency" value="0" class="form__radiobutton" {% if not task.urgency %}checked{% endif %} id="id_urgency" >
                                <span class="form__radiobutton-text">Не срочно</span>
                            </label>
                        </div>
                    </section>

                    <section class="form__item">
                        <span class="form__text">Важность:</span>
                        <div class="form__wrapper">
                            <label class="form__label">
                                <input type="radio" name="importancy" value="1" class="form__radiobutton" {% if task.importancy %}checked{% endif %} id="id_importancy" required>
                                <span class="form__radiobutton-text">Важно</span>
                            </label>
                            <label class="form__label">
                                <input type="radio" name="importancy" value="0" {% if not task.importancy %}checked{% endif %} class="form__radiobutton" id="id_importancy">
                                <span class="form__radiobutton-text">Не важно</span>
                            </label>
                        </div>
                    </section>

                    {% if form.errors %}
                    <section class="form__item form__item_errors">

                        {% for field, errors in form.errors.items %}
                            {% for error in errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        {% endfor %}
                    </section>
                        
                    {% endif %}

                    <button type="submit" class="btn form__submit">Изменить</button>
                </form>
            </section>

            <section class="tab" id="delete_task">
                <form action="{% url "tasks:delete_task" task.id %}" class="form" method="post">
                    {% csrf_token %}
                    <h2 class="form__h2">Вы действительно хотите удалить задачу?</h2>
                    <button type="submit" class="btn form__submit">Да, удалить</button>
                </form>
            </section>
        </div>

        {% if task.is_active %}
            <footer class="modal__footer">
                <div class="tabs-switcher">
                    <div class="tabs-switcher__item">
                        <a href="{% url "tasks:complate_task" task.id  %}" class="btn btn_complate-task tabs-switcher__btn"><i class="fa-solid fa-check tabs-switcher__icon"></i>Выполнить</a>
                        <button class="btn tabs-switcher__btn tabs-switcher__btn_open btn_update-task" data-open="update_task"><i class="fa-solid fa-pen tabs-switcher__icon"></i>Изменить</button>
                        <button class="btn tabs-switcher__btn tabs-switcher__btn_open btn_delete-task" data-open="delete_task"><i class="fa-solid fa-trash-can tabs-switcher__icon"></i>Удалить</button>
                        <!-- <a href="" class="btn tabs-switcher__btn"></a> -->
                    </div>
                    <div class="tabs-switcher__item tabs-switcher__item_hidden">
                        <button class="btn tabs-switcher__btn tabs-switcher__btn_close" data-open="task_info"><i class="fa-solid fa-arrow-left tabs-switcher__icon"></i>Назад</button>
                    </div>
                </div>
            </footer>
        {% endif %}
    </div>
    <div class="modal__overlay"></div>
</article>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "fontawesome-free-6.5.1-web/webfonts/fa-regular-400.ttf" %}">
    <link rel="stylesheet" href="{% static "fontawesome-free-6.5.1-web/css/all.min.css" %}">
    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <title>{{ title }}</title>
</head>
<body>
    <header class="header">
        <div class="container">
            <div class="header__wrapper">
                <h1 class="header__h1">Easyhower</h1>
                <button class="btn btn_menu btn_mobile">
                    <i class="fa fa-bars" aria-hidden="true"></i>
                </button>
                <nav class="navigation">
                    <article class="menu">
                        <header class="menu__header">
                        <h3 class="menu__h3">Меню</h3>
                        <button class="btn btn_menu btn_mobile">
                            <i class="fa fa-times" aria-hidden="true"></i>
                        </button>
                        </header>
                        <ul class="menu__list">
                            <li class="menu__item">
                                <a href="/" class="menu__link"><i class="fa-solid fa-house menu__icon"></i>Главная</a>
                            </li>
                            {% if not user.is_authenticated %}
                            <li class="menu__item">
                                <a href="{% url "user:login" %}" class="menu__link"><i class="fa-solid fa-arrow-right-to-bracket menu__icon"></i>Войти</a>
                            </li>
                            {% else %}
                            {% if user.is_admin or user.is_staff %}
                            <li class="menu__item">
                                <a href="{% url "admin:index" %}" class="menu__link"><i class="fa-solid fa-toolbox menu__icon"></i>Админка</a>
                            </li>
                            {% endif %}
                            <li class="menu__item">
                                <a href="{% url "user:profile" %}" class="menu__link"><i class="fa-solid fa-user menu__icon"></i>Профиль - {{ user.username }}</a>
                            </li>
                            <li class="menu__item">
                                <a href="{% url "tasks:tasks" %}" class="menu__link"><i class="fa-solid fa-table menu__icon"></i>К задачам</a>
                            </li>
                            <li class="menu__item">
                                <a href="{% url "user:logout" %}" class="menu__link"><i class="fa-solid fa-arrow-right-from-bracket menu__icon"></i>Выйти</a>
                            </li>
                            {% endif %}
                        </ul>
                    </article>
                    
                    <div class="navigation__overlay">
                </nav>
            </div>
            
        </div>
    </header>
    <main class="main">
        {% block content %}{% endblock  %}
    </main>
    <footer class="footer">
        <div class="container">
            <p class="footer__text">&copy; Таблица Эйзенхауэра by justP</p>
        </div>
    </footer>
    <script src="{% static "js/main.js" %}"></script>
</body>
</html>

user/templates/user/profile.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<section class="profile">
    <div class="container">
        <h2 class="profile__h2">Профиль</h2>
        {% comment %} TODO: Данные пользователя {% endcomment %}
        <article class="statistics">
            <h2 class="statistics__h2">Статистика</h2>
            <p class="statistics__p">Выполнено задач: <span class="statistics__counter">{{ user.complate_tasks_quantity }}</span></p>
        </article>

        {% comment %} TODO: Выполненые задачи {% endcomment %}
        <article class="cell cell_completed">
            <header class="cell__header cell__header_completed">
                <h3 class="cell__h3 cell__h3_completed">Выполненые задачи</h3>
                <button class="btn cell__btn" title="Свернуть">
                    <i class="cell__icon cell__icon_completed fa fa-caret-down" aria-hidden="true"></i>
                </button>
            </header>
            <div class="cell__body cell__body_completed">
                <ol class="cell__list">
                    {% for task in tasks %}
                        <li class="task"><a href="{% url "tasks:read_task" task.id %}" class="task__link" data-target="read_task">{{ task.name }}</a></li>
                    {% endfor %}
                    
                </ol>
            </div>
        </article>
        
        <article class="personal-data">
            <h2 class="personal-data__h2">Смена пароля</h2>
            <form action="{% url "user:password_change" %}" class="form" method="post">
                {% csrf_token %}
                <section class="form__item">
                    <label class="form__label" for="id_old_password">
                        <span class="form__text">Старый пароль:</span>
                    </label>
                    <input type="password" name="old_password" class="form__input" id="id_old_password" required>
                </section>

                <section class="form__item">
                    <label class="form__label" for="new_password1">
                        <span class="form__text">Новый пароль:</span>
                    </label>
                    <input type="password" name="new_password1" class="form__input" id="new_password1" required>
                </section>
                
                <section class="form__item">
                    <label class="form__label" for="new_password2">
                        <span class="form__text">Подтверди пароль:</span>
                    </label>
                    <input type="password" name="new_password2" class="form__input" id="new_password2" required>
                </section>

                {% if form.errors %}
                <section class="form__item form__item_errors">

                    {% for field, errors in form.errors.items %}
                        {% for error in errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    {% endfor %}
                </section>
                    
                {% endif %}
                <button type="submit" class="btn form__submit">Сохранить</button>
            </form>
        </article>
    </div>


</section>
{% endblock %}

user/templates/user/registration.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<section class="form-wrapper">
    <div class="container">
        <form action="{% url "user:registration" %}" class="form form_big" method="post">
            {% csrf_token %}
            <section class="form__item">
                <label class="form__label" for="id_username">
                    <span class="form__text">Имя пользователя:</span>
                </label>
                <input type="text" name="username" class="form__input" id="id_username" required>
            </section>

            <section class="form__item">
                <label class="form__label" for="id_email">
                    <span class="form__text">E-mail:</span>
                </label>
                <input type="email" name="email" class="form__input" id="id_email" required>
            </section>
            
            <section class="form__item">
                <label class="form__label" for="id_password1">
                    <span class="form__text">Пароль:</span>
                </label>
                <input type="password" name="password1" class="form__input" id="id_password1" required>
            </section>
            
            <section class="form__item">
                <label class="form__label" for="id_password2">
                    <span class="form__text">Подтверди пароль:</span>
                </label>
                <input type="password" name="password2" class="form__input" id="id_password2" required>
            </section>

            {% if form.errors %}
            <section class="form__item form__item_errors">

                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <p>{{ error }}</p>
                    {% endfor %}
                {% endfor %}
            </section>
                
            {% endif %}
            
            <button type="submit" class="btn form__submit">Зарегистрироваться</button>
            <hr>
            <div class="already-registered">
                <p class="already-registered__text">Уже есть аккаунт?
                    <a href="{% url "user:login" %}" class="already-registered__link">Войти</a>
                </p>
            </div>
        </form>
    </div>
</section>
{% endblock  %}